# Mnist digit classification

The first task this week is to classify the Mnist digit dataset using a deep neural network. You will use
the Keras interface, which sits between you and TensorFlow.

This exercise is taken from a TensorFlow tutorial, which provides an excellent introduction to building deep
neural networks.

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

Define the input layer. This will be taking the raw pixel values, and there are 784 of them
(the images have 28x28 pixels).

In [2]:
inputs = tf.keras.Input(shape=(784,))

We can now define our first layer of hidden neurons. These will start to convolve the inputs to extract features.
It will process the `inputs` variable defined in the previous step and produce an output called x. We will go
from 784-dimensional inputs to 64-dimensions.

In [7]:
dense = layers.Dense(64, activation="relu")
x = dense(inputs)

We then add the next layer, which further extracts features. This will process x from the previous step and result in a new x that is also 64-dimensional, before passing those outputs to a final layer that is 10-dimensional - the outputs of that layer go into a variable called `outputs`.

In [8]:
x = layers.Dense(64, activation="relu")(x)
outputs = layers.Dense (10)(x)

Each of those outputs represents one of the digits. 

Having defined the layers of the network we can now construct the model.

In [9]:
model = tf.keras.Model(inputs=inputs, outputs=outputs, name = "mnist_model")
model.summary()

Model: "mnist_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 784)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 64)                  │          50,240 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 64)                  │           4,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 55,050 (215.04 KB)

 Trainable params: 55,050 (215.04 KB)

 Non-trainable params: 0 (0.00 B)

Like `Scikit`, `Keras` comes with some test datasets - one of which is the Mnist digit classification task we've spoken about previously. The images’ pixels are on the range 0 to 255 - we want them between 0 and 1, so normalise them by  dividing by 255


In [12]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

X_train = X_train.reshape(60_000, 784).astype("float32")/255
X_test = X_test.reshape(10_000, 784).astype("float32")/255

Having loaded the data, compile it as follows. You will need to specify a loss function (to determine how good the predictions are), an optimiser, and accuracy metrics to report on how well the predictions do. You can then train the model.


In [13]:
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(X_train, y_train, batch_size=64, epochs=2, validation_split = 0.2)

test_scores = model.evaluate(X_test, y_test, verbose=2)
print(f"Test Accuracy: {test_scores[1]}")

Epoch 1/2
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8364 - loss: 0.5967 - val_accuracy: 0.9477 - val_loss: 0.1807
Epoch 2/2
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9512 - loss: 0.1692 - val_accuracy: 0.9593 - val_loss: 0.1367
313/313 - 0s - 696us/step - accuracy: 0.9621 - loss: 0.1328
Test Accuracy: 0.9621000289916992


```
Epoch 1/2
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8364 - loss: 0.5967 - val_accuracy: 0.9477 - val_loss: 0.1807
Epoch 2/2
750/750 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9512 - loss: 0.1692 - val_accuracy: 0.9593 - val_loss: 0.1367
313/313 - 0s - 696us/step - accuracy: 0.9621 - loss: 0.1328
Test Accuracy: 0.9621000289916992
```